/**
 * `loom env` — keep `.env` in sync with `.env.example`.
 *
 * The most common "works on my machine" bug is a missing env var. This diffs
 * the two files and, with `--sync`, appends any keys the example declares but
 * `.env` is missing (values left blank for the developer to fill).
 *
 * Pure dotenv-style parsing — no dependency on the `dotenv` package.
 */
import { existsSync, readFileSync, writeFileSync, appendFileSync } from "node:fs";
import path from "node:path";
import { reporterFromOptions } from "../services/index.js";

/** Parse `KEY=value` lines into an ordered list of keys (comments/blanks skipped). */
export function parseEnvKeys(content) {
  const keys = [];
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq > 0) keys.push(line.slice(0, eq).trim());
  }
  return keys;
}

/**
 * @param {object} [options] - global flags plus:
 * @param {boolean} [options.sync] - append missing keys to .env
 * @param {string} [options.projectRoot]
 * @param {object} [options.reporter]
 */
export default async function env(options = {}) {
  const reporter = options.reporter ?? reporterFromOptions(options);
  const projectRoot = options.projectRoot ?? process.cwd();
  const examplePath = path.join(projectRoot, ".env.example");
  const envPath = path.join(projectRoot, ".env");

  if (!existsSync(examplePath)) {
    reporter.warn("No .env.example found — nothing to compare against.");
    reporter.result({ missing: [], synced: false });
    reporter.flush();
    return { missing: [], synced: false };
  }

  const exampleKeys = parseEnvKeys(readFileSync(examplePath, "utf-8"));
  const currentKeys = existsSync(envPath)
    ? new Set(parseEnvKeys(readFileSync(envPath, "utf-8")))
    : new Set();
  const missing = exampleKeys.filter((key) => !currentKeys.has(key));

  if (missing.length === 0) {
    reporter.success(".env is in sync with .env.example");
    reporter.result({ missing: [], synced: false });
    reporter.flush();
    return { missing: [], synced: false };
  }

  reporter.warn(`${missing.length} key(s) missing from .env: ${missing.join(", ")}`);

  let synced = false;
  if (options.sync) {
    const block = `${missing.map((key) => `${key}=`).join("\n")}\n`;
    if (existsSync(envPath)) appendFileSync(envPath, `\n# Added by 'loom env --sync'\n${block}`);
    else writeFileSync(envPath, `# Generated by 'loom env --sync'\n${block}`);
    synced = true;
    reporter.success(`Appended ${missing.length} key(s) to .env — fill in the values.`);
  } else {
    reporter.info("Run 'loom env --sync' to append the missing keys.");
    process.exitCode = 1;
  }

  reporter.result({ missing, synced });
  reporter.flush();
  return { missing, synced };
}
