#!/usr/bin/env node

/**
 * `loom usage` — writes CLI_USAGE.md to the project root.
 *
 * The file contains a full reference of every command with options.
 * It is NOT auto-generated into projects — the user explicitly requests it.
 * `loom cleanup` removes CLI_USAGE.md as part of starter metadata.
 */

import path from "node:path";
import fs from "node:fs";
import chalk from "chalk";

const CONTENT = `# Stackloom CLI Usage Reference

> Auto-generated by \`loom usage\`. Run \`loom cleanup\` to remove this file.

---

## Getting Started

| Command | Description |
|---|---|
| \`loom init <name>\` | Create a new project from the starter kit template |
| \`loom wizard\` | Interactive guide to extend your project after init |

---

## Generate

### \`loom generate resource <name>\`

Generate a full-stack resource (model, controller, routes, validator, frontend pages).

| Option | Description |
|---|---|
| \`--fields <spec>\` | Field spec: \`name:type:rules;...\` (e.g. \`email:email:required\|unique\`) |
| \`--file <path>\` | Path to a resource definition file |
| \`--arch <level>\` | Architecture: \`lightweight\` | \`moderate\` | \`advanced\` (default: moderate) |
| \`--relations <spec>\` | Virtual hasMany: \`field:hasMany:Model:foreignKey\` (repeat with \`;\`) |
| \`--crud <mode>\` | CRUD scope: \`full\` | \`insert-only\` (default: full) |
| \`--form-mode <mode>\` | Form display: \`page\` | \`modal\` | \`sidepanel\` | \`inline\` |
| \`--with-tests\` | Generate test files |
| \`--no-frontend\` | Skip frontend generation |
| \`--interactive\` | Prompt interactively for missing details |
| \`--amend\` | Update an existing resource, preserve custom code zones |
| \`--remove-fields <list>\` | Remove fields by name on amend (comma-separated) |
| \`--force\` | Overwrite files without AUTO-GENERATED markers |
| \`--dry-run\` | Preview file plan without writing |
| \`--preview\` | Show estimated file count, time, and planned files before generating |

### \`loom resource sync <name>\`

Alias for \`generate resource --amend\`. Merge fields, preserve custom code zones.

### \`loom resource add-field <name> [field-spec]\`

Add a single field to an existing resource.

| Option | Description |
|---|---|
| \`--interactive\` | Prompt interactively for the field to add |
| \`--force\` | Overwrite files without AUTO-GENERATED markers |

### \`loom generate module <name>\`

Generate backend module (model, service, controller, routes, validator).

| Option | Description |
|---|---|
| \`--fields <spec>\` | Field specification |
| \`--arch <level>\` | Architecture: \`lightweight\` | \`moderate\` | \`advanced\` |
| \`--interactive\` | Prompt for fields interactively |
| \`--with-page\` | Generate corresponding frontend page |
| \`--form-mode <mode>\` | Form mode if \`--with-page\`: \`page\` | \`modal\` | \`sidepanel\` | \`inline\` |
| \`--force\` | Overwrite existing files |

### \`loom generate page <name>\`

Generate frontend page with route and nav entry.

| Option | Description |
|---|---|
| \`--route <path>\` | Custom route path |
| \`--no-nav\` | Do not add to navigation |
| \`--icon <name>\` | Icon name from lucide-react |
| \`--with-form\` | Generate form component |
| \`--form-mode <mode>\` | Form display: \`page\` | \`modal\` | \`sidepanel\` | \`inline\` |
| \`--form-fields <spec>\` | Form field specification |
| \`--interactive\` | Prompt for form fields interactively |
| \`--force\` | Overwrite existing files |

### \`loom generate theme\`

Import a shadcn/ui theme from CSS variables.

| Option | Description |
|---|---|
| \`--file <path>\` | Path to CSS file with \`:root\` / \`.dark\` |
| \`--paste <css>\` | CSS string directly |
| \`--fallback <theme>\` | Fallback theme name |
| \`--appearance <recipe>\` | Appearance: \`elevated\` | \`flat\` | \`ux-heavy\` |
| \`--apply\` | Update \`app-preset.js\` automatically |

### \`loom generate deploy\`

Generate deployment configs.

| Option | Description |
|---|---|
| \`--target <provider>\` | Target: \`docker\` | \`vercel\` | \`railway\` | \`all\` |
| \`--force\` | Overwrite existing files |

---

## Scaffold

### \`loom scaffold <scenario>\`

Generate a complete scenario preset (resources, fields, relations, pages).

| Scenario | Description |
|---|---|
| \`parking\` | Parking management — slots, vehicles, tickets |
| \`payroll\` | Payroll management — departments, employees, timesheets, payroll |
| \`inventory\` | Inventory management — categories, products, suppliers, stock movements |
| \`booking\` | Booking management — customers, services, bookings |
| \`delivery\` | Delivery management — drivers, routes, packages, orders |

---

## Validate

### \`loom validate <scenario>\`

Audit your project against a scenario checklist. Reports which entities, fields, and files are present or missing. Uses loose field-name matching (e.g. \`telephone\` ≈ \`phone\`).

---

## Customize

### \`loom customize theme set [theme]\`

Switch to a built-in theme.

### \`loom customize theme import\`

Import a custom shadcn/ui theme from CSS.

### \`loom customize layout set [layout]\`

Switch layout shell.

### \`loom customize brand set\`

Update brand name and/or tagline.

| Option | Description |
|---|---|
| \`--name <text>\` | New brand name |
| \`--tagline <text>\` | New tagline |

### \`loom customize data set [template]\`

Switch data display template.

### \`loom customize ui set [variant]\`

Switch card, modal, select, and pagination styles.

### \`loom customize font set [font]\`

Set body and heading fonts (Google Fonts auto-import).

| Option | Description |
|---|---|
| \`--heading <font>\` | Heading font name (defaults to body font) |

### \`loom customize css\`

Inject custom CSS rules.

| Option | Description |
|---|---|
| \`--file <path>\` | Path to CSS file with rules to inject |
| \`--css <rules>\` | CSS rules string directly |

**Discovery commands:**

\`loom customize list-themes\` — List available built-in themes
\`loom customize list-layouts\` — List available layout shells
\`loom customize list-data\` — List available data display templates
\`loom customize theme preset apply <code>\` — Resolve a shadcn preset code and apply its CSS variables
\`loom customize theme preset save <name>\` — Save current imported theme as a named preset in .loom/themes/
\`loom customize theme preset list\` — List locally saved theme presets
\`loom customize theme preset open\` — Open shadcn/create in browser to build a custom preset

\`loom customize list-ui\` — List available UI variant presets
\`loom customize list-fonts\` — List available font presets
---

## Reports

### \`loom add-report [name]\`

Generate an aggregation pipeline report with backend API and frontend page.

| Option | Description |
|---|---|
| \`--model <name>\` | Mongoose model name (PascalCase) |
| \`--title <text>\` | Human-readable report title |
| \`--description <text>\` | Report description |
| \`--group-by <field>\` | Group by field |
| \`--agg-fn <fn>\` | Aggregation function: \`sum\` | \`count\` | \`avg\` | \`min\` | \`max\` |
| \`--agg-field <name>\` | Result field name |
| \`--agg-target <field>\` | Aggregate on field |
| \`--sort-by <field>\` | Sort by field |
| \`--sort-order <order>\` | Sort order: \`asc\` | \`desc\` |
| \`--interactive\` | Prompt for all report details |
| \`--no-frontend\` | Skip frontend generation |

---

## Project Health

| Command | Description |
|---|---|
| \`loom doctor\` | Check environment and project health |
| \`loom check\` | Verify project structure, blueprint, anchors, env |
| \`loom completion [bash|zsh]\` | Generate shell completion script for tab-completion |
| \`loom upgrade [--write]\` | Check CLI vs template compatibility; apply upgrade |
| \`loom explain\` | Show project overview: resources, routes, modules, theme, auth, env |

### \`loom backup\`

Manage upgrade backups.

| Subcommand | Description |
|---|---|
| \`list\` | List available upgrade backups |
| \`restore <id>\` | Restore project from a backup |

---

## Lifecycle

| Command | Description |
|---|---|
| \`loom remove <type> <name>\` | Remove a generated page or module |
| \`loom usage\` | Write CLI_USAGE.md reference to project root |
| \`loom cleanup [preset]\` | De-brand project (\`minimal\` | \`production\` | \`template\`) |
| \`loom finalize\` | Prepare project for production (lint, test, build) |
| \`loom rollback\` | Undo the last generation action |
| \`loom env [--sync]\` | Diff / sync \`.env\` with \`.env.example\` |

---

## Configuration

| Command | Description |
|---|---|
| \`loom preset [name]\` | Apply a predefined configuration preset (\`saas\`, \`clinic\`, etc.) |
| \`loom rename <new-name>\` | Rebrand the CLI command name |
| \`loom make:resource [name]\` | Create resource from schema or interactive wizard |

---

## Programmatic API

Every CLI command is available as a JavaScript module. Import from \`stackloom-cli/api\`:

\`\`\`js
import { doctor, validate, generateResource } from "stackloom-cli/api";

const result = await doctor();
console.log(result.ok, result.output.stdout);
\`\`\`

Each function returns \`{ ok, data, error, output: { stdout, stderr } }\`.

**Available exports:** \`doctor\`, \`check\`, \`explain\`, \`validate\`, \`usage\`, \`generateResource\`, \`scaffold\`, \`addReport\`, \`wizard\`, \`customizeTheme\`, \`cleanup\`, \`rollback\`, \`finalize\`, \`env\`, \`preset\`, \`init\`, \`command\`, \`run\`.

---

## Shell Completion

Generate bash or zsh completion scripts for tab-completion of all commands, subcommands, and flags:

\`\`\`bash
source <(loom completion bash)    # Activate for current session
loom completion bash > ~/.loom-completion.bash  # Install permanently
echo "source ~/.loom-completion.bash" >> ~/.bashrc
\`\`\`

\`\`\`bash
source <(loom completion zsh)     # Activate for current session
loom completion zsh > /usr/local/share/zsh/site-functions/_loom  # Install permanently
\`\`\`

---

## Global Flags

| Flag | Description |
|---|---|
| \`-q, --quiet\` | Errors and warnings only |
| \`--json\` | Structured JSON output for scripts |
| \`--no-color\` | Disable ANSI colour |
| \`--debug\` | Show diagnostic detail |
| \`-y, --yes\` | Assume defaults, never prompt |
| \`--brief\` | Less verbose output |
| \`--help\` | Show help for any command |
| \`--version\` | Show CLI version |

---

## Field Spec Format

\`\`\`
name:type[rules]:validation
\`\`\`

**Examples:**

\`\`\`
name:string:required
email:email:required|unique
age:number:required|min=18|max=120
category:ref[Category]:required
tags:multiselect[a,b,c]
status:string:default=pending
\`\`\`

**Supported types:** \`string\`, \`text\`, \`number\`, \`boolean\`, \`email\`, \`password\`, \`phone\`, \`url\`, \`date\`, \`datetime\`, \`color\`, \`file\`, \`range\`, \`ref\`, \`select\`, \`multiselect\` (and short aliases: \`str\`, \`num\`, \`bool\`).

**Validation rules:** \`required\`, \`unique\`, \`min=N\`, \`max=N\`, \`minLength=N\`, \`maxLength=N\`, \`default=X\`, \`pattern=REGEX\`.

---

## Relations Spec Format

\`\`\`
virtualField:hasMany:TargetModel:foreignKeyInChild
\`\`\`

**Example:** \`orders:hasMany:Order:customerId\` — adds a virtual \`orders\` field on the current model that resolves to Order documents where \`customerId\` equals this doc's \`_id\`.

Multiple relations can be separated with \`;\`.

---

## Form Modes

| Mode | Description |
|---|---|
| \`page\` | Form takes over the page (dedicated route) |
| \`modal\` | Form opens in a centered dialog overlay |
| \`sidepanel\` | Form slides in from the right as a sheet |
| \`inline\` | Form is always visible above the table |

Project default can be set in \`.loom/blueprint.json\` under \`defaults.formMode\`.

---

## Exit Codes

| Code | Meaning |
|---|---|
| \`0\` | Success |
| \`1\` | Command failed / validation error |
| \`2\` | Invalid input or missing arguments |
`;

export default async function usageCmd(options = {}) {
  const projectRoot = options.projectRoot || process.cwd();
  const targetPath = path.join(projectRoot, "CLI_USAGE.md");

  try {
    fs.writeFileSync(targetPath, CONTENT, "utf-8");
    console.log(chalk.green(`\n✓ CLI_USAGE.md written to ${targetPath}\n`));
    console.log(chalk.dim("Run `loom cleanup` to remove this file from the project.\n"));
    return { ok: true, path: targetPath };
  } catch (err) {
    console.error(chalk.red(`✖ Failed to write CLI_USAGE.md: ${err.message}`));
    return { ok: false, error: err.message };
  }
}
